Repository 20tyamato/42ft_transcendence, pull requests merged in 2025-02, with the labels that each got.

#166 FIX: rm BlockchainScore, Tournament in models.py #162
  api/pong/admin.py
  api/pong/migrations/0007_remove_tournament_games_and_more.py
  api/pong/models.py
  api/pong/permissions.py
  api/pong/serializers.py
  api/pong/tests/test_model.py
  api/pong/urls.py
  api/pong/views.py
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/ja.json
  frontend/src/main.ts
  frontend/src/pages/Profile/index.ts
Labels: Type: improvement

#154 FIX: show canvas #153
  frontend/package-lock.json
  frontend/package.json
  frontend/public/models/scene.bin
  frontend/public/models/scene.glb
  frontend/public/models/scene.gltf
  frontend/src/pages/Result/index.ts
  frontend/src/pages/SinglePlay/Game/Ball.ts
  frontend/src/pages/SinglePlay/Game/Experience.ts
  frontend/src/pages/SinglePlay/Game/Field.ts
  frontend/src/pages/SinglePlay/Game/LocalGame.ts
  frontend/src/pages/SinglePlay/Game/Paddle.ts
  frontend/src/pages/SinglePlay/Game/Wall.ts
  frontend/src/pages/SinglePlay/Game/index.html
  frontend/src/pages/SinglePlay/Game/index.ts
  frontend/src/pages/SinglePlay/Game/logic.ts
  frontend/src/pages/SinglePlay/Game/score.ts
  frontend/src/pages/SinglePlay/Game/style.css
  frontend/src/pages/SinglePlay/Utils/EventEmitter.ts
  frontend/src/pages/SinglePlay/Utils/Loaders.ts
  frontend/src/pages/SinglePlay/Utils/Renderer.ts
  frontend/src/pages/SinglePlay/Utils/Sizez.ts
  frontend/src/pages/SinglePlay/Utils/Time.ts
  frontend/src/pages/SinglePlay/Utils/sources.ts
  frontend/src/pages/SinglePlay/World/Camera.ts
  frontend/src/pages/SinglePlay/World/CameraLerp.ts
  frontend/src/pages/SinglePlay/World/Model.ts
  frontend/src/pages/SinglePlay/World/World.ts
Labels: Problem: bug, Type: improvement, WIP

#177 FIX: リファクタリング PART 2 #135
  api/pong/fixtures/initial_data.json
  api/pong/migrations/0010_remove_tournamentgamesession_max_players_and_more.py
  frontend/src/layouts/common/close.png
  frontend/src/layouts/common/index.html
  frontend/src/layouts/common/index.ts
  frontend/src/layouts/common/style.css
  frontend/src/layouts/loggedin/index.html
  frontend/src/layouts/loggedin/style.css
  frontend/src/locales/en.json
  frontend/src/locales/fr.json
  frontend/src/locales/ja.json
  frontend/src/models/Lang/repository.ts
  frontend/src/models/User/auth.ts
  frontend/src/models/User/repository.ts
  frontend/src/models/Window/repository.ts
  frontend/src/pages/404/index.html
  frontend/src/pages/404/index.ts
  frontend/src/pages/404/style.css
  frontend/src/pages/Friends/index.html
  frontend/src/pages/Friends/index.ts
  frontend/src/pages/GameModes/index.ts
  frontend/src/pages/Home/index.ts
  frontend/src/pages/Leaderboard/index.ts
  frontend/src/pages/Login/index.ts
  frontend/src/pages/Logout/index.ts
  frontend/src/pages/Modes/index.ts
  frontend/src/pages/Profile/index.html
  frontend/src/pages/Profile/index.ts
  frontend/src/pages/Register/index.ts
  frontend/src/pages/Settings/User/index.html
  frontend/src/pages/Settings/User/index.ts
  frontend/src/pages/SinglePlay/Select/index.html
  frontend/src/pages/SinglePlay/Select/index.ts
  frontend/src/pages/SinglePlay/Select/style.css
  frontend/src/resources/42_logo.svg
  frontend/src/resources/avatar.png
  frontend/src/resources/background.png
  frontend/src/resources/logout.png
  frontend/src/utils/language.ts
  frontend/src/utils/updateElements.ts
Labels: WIP

#194 FIX: リファクタリング PART 4 #135
  .vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/Friends/index.html
  frontend/src/pages/Home/index.html
  frontend/src/pages/Modes/index.ts
  frontend/src/pages/MultiPlay/Game/index.html
  frontend/src/pages/MultiPlay/Game/index.ts
  frontend/src/pages/MultiPlay/Game/style.css
  frontend/src/pages/MultiPlay/Test/index.ts
  frontend/src/pages/MultiPlay/Waiting/index.html
  frontend/src/pages/MultiPlay/Waiting/index.ts
  frontend/src/pages/MultiPlay/index.html
  frontend/src/pages/SinglePlay/Select/index.html
  frontend/src/pages/Tournament/Waiting/index.html
  frontend/src/pages/Tournament/Waiting/index.ts
  frontend/src/pages/Tournament/Waiting/style.css
  frontend/src/pages/Tournament/index.html
  frontend/src/pages/Tournament/index.ts
  frontend/src/pages/Tournament/style.css
  package-lock.json
  package.json
Labels: WIP

#198 FIX: リファクタリング PART 6 #135
  api/core/settings.py
  api/pong/middleware.py
  api/pong/migrations/0012_user_last_activity.py
  api/pong/models.py
  api/pong/urls.py
  api/pong/views.py
  frontend/src/models/User/auth.ts
  frontend/src/models/User/repository.ts
  frontend/src/models/interface.ts
  frontend/src/pages/404/index.ts
  frontend/src/pages/Friends/index.ts
  frontend/src/pages/Home/index.ts
  frontend/src/pages/Leaderboard/index.ts
  frontend/src/pages/Login/index.ts
  frontend/src/pages/Logout/index.ts
  frontend/src/pages/MultiPlay/Game/game_renderer.ts
  frontend/src/pages/MultiPlay/Game/index.html
  frontend/src/pages/MultiPlay/Game/index.ts
  frontend/src/pages/MultiPlay/Game/style.css
  frontend/src/pages/MultiPlay/Test/index.ts
  frontend/src/pages/MultiPlay/Waiting/index.html
  frontend/src/pages/MultiPlay/Waiting/index.ts
  frontend/src/pages/MultiPlay/Waiting/style.css
  frontend/src/pages/MultiPlay/index.html
  frontend/src/pages/MultiPlay/index.ts
  frontend/src/pages/MultiPlay/style.css
  frontend/src/pages/Profile/index.ts
  frontend/src/pages/Register/index.ts
  frontend/src/pages/Result/index.html
  frontend/src/pages/Result/index.ts
  frontend/src/pages/Result/style.css
  frontend/src/pages/Settings/User/index.ts
  frontend/src/pages/SinglePlay/Game/index.ts
  frontend/src/pages/SinglePlay/Select/index.ts
  frontend/src/pages/Tournament/Waiting/index.ts
  frontend/src/pages/Tournament/index.ts
Labels: WIP
