Repository 20tyamato/42ft_transcendence, pull requests merged in 2025-03, with the labels that each got.

#208 ADD: マルチプレイゲームの設計やり直し #207
  api/pong/base_consumers.py
  api/pong/consumers.py
  api/pong/fixtures/initial_data.json
  api/pong/game_logic.py
  api/pong/migrations/0001_initial.py
  api/pong/migrations/0002_tournament_blockchainscore.py
  api/pong/migrations/0003_alter_game_player2.py
  api/pong/migrations/0004_user_experience.py
  api/pong/migrations/0005_gamesession.py
  api/pong/migrations/0006_user_language.py
  api/pong/migrations/0007_remove_tournament_games_and_more.py
  api/pong/migrations/0008_user_friends_user_is_online.py
  api/pong/migrations/0009_tournamentgamesession_tournamentmatch_and_more.py
  api/pong/migrations/0010_remove_tournamentgamesession_max_players_and_more.py
  api/pong/migrations/0011_tournamentsession_and_more.py
  api/pong/migrations/0012_user_last_activity.py
  api/pong/models.py
  api/pong/serializers.py
  frontend/src/models/MultiPlay/MultiplayerGameManager.ts
  frontend/src/models/Services/BaseGameManager.ts
  frontend/src/models/Services/InputHandlerService.ts
  frontend/src/models/Services/WebSocketService.ts
  frontend/src/models/Services/game_renderer.ts
  frontend/src/models/interface.ts
  frontend/src/pages/MultiPlay/Game/index.ts
  frontend/src/pages/SinglePlay/Game/Ball.ts
  frontend/src/pages/SinglePlay/Game/Field.ts
  frontend/src/pages/SinglePlay/Game/Wall.ts
  frontend/src/pages/SinglePlay/Game/World/Camera.ts
  frontend/src/pages/Tournament/Bracket/BracketDisplay.ts
Labels: Type: cleanup, Type: improvement

#214 Hrinka2/add game logic#211
  .zshrc
  frontend/src/pages/SinglePlay/Game/Ball.ts
  frontend/src/pages/SinglePlay/Game/Experience.ts
  frontend/src/pages/SinglePlay/Game/Field.ts
  frontend/src/pages/SinglePlay/Game/LocalGame.ts
  frontend/src/pages/SinglePlay/Game/Paddle.ts
  frontend/src/pages/SinglePlay/Game/Wall.ts
  frontend/src/pages/SinglePlay/Game/World/Camera.ts
  frontend/src/pages/SinglePlay/Game/index.html
  frontend/src/pages/SinglePlay/Game/index.ts
  frontend/src/pages/SinglePlay/Game/style.css
Labels: WIP

#217 Hrinka2/add show result#215
  frontend/src/pages/Result/index.ts
  frontend/src/pages/SinglePlay/Game/Ball.ts
  frontend/src/pages/SinglePlay/Game/Experience.ts
  frontend/src/pages/SinglePlay/Game/Field.ts
  frontend/src/pages/SinglePlay/Game/LocalGame.ts
  frontend/src/pages/SinglePlay/Game/index.html
  frontend/src/pages/SinglePlay/Game/index.ts
  frontend/src/pages/SinglePlay/Game/style.css
  frontend/src/pages/SinglePlay/Select/index.html
  package-lock.json
  package.json
Labels: Type: design, Type: improvement, Type: new feature, WIP

#213 ADD: トーナメント機能 #212
  api/pong/consumers.py
  api/pong/migrations/0001_initial.py
  api/pong/models.py
  api/pong/serializers.py
  api/pong/tests/test_model.py
  api/pong/tests/test_serializers.py
  frontend/src/main.ts
  frontend/src/models/Tournament/repository.ts
  frontend/src/models/interface.ts
  frontend/src/pages/MultiPlay/Waiting/index.ts
  frontend/src/pages/MultiPlay/index.ts
  frontend/src/pages/Tournament/Bracket/BracketDisplay.ts
  frontend/src/pages/Tournament/Bracket/index.html
  frontend/src/pages/Tournament/Bracket/index.ts
  frontend/src/pages/Tournament/Bracket/style.css
  frontend/src/pages/Tournament/Ready/index.html
  frontend/src/pages/Tournament/Ready/index.ts
  frontend/src/pages/Tournament/Ready/style.css
Labels: Type: new feature, WIP

#229 Akamite/fix login bug
  api/core/settings.py
  api/pong/modules/Auth/serializers.py
  api/pong/modules/Auth/views.py
  api/pong/serializers.py
  api/pong/urls.py
  api/pong/views.py
  docker-compose.yml
  frontend/src/core/Layout.ts
  frontend/src/core/Logger.ts
  frontend/src/core/Page.ts
  frontend/src/layouts/AuthLayout/index.html
  frontend/src/layouts/AuthLayout/index.ts
  frontend/src/layouts/AuthLayout/style.css
  frontend/src/layouts/common/index.ts
  frontend/src/libs/Auth/currnetUser.ts
  frontend/src/libs/localStorage.ts
  frontend/src/main.ts
  frontend/src/models/Game/repository.ts
  frontend/src/models/User/auth.ts
  frontend/src/models/User/repository.ts
  frontend/src/models/User/type.ts
  frontend/src/models/interface.ts
  frontend/src/pages/Friends/index.ts
  frontend/src/pages/Home/index.ts
  frontend/src/pages/Leaderboard/index.ts
  frontend/src/pages/Login/index.ts
  frontend/src/pages/Logout/index.html
  frontend/src/pages/Logout/index.ts
  frontend/src/pages/Modes/index.ts
  frontend/src/pages/MultiPlay/Game/index.ts
  frontend/src/pages/MultiPlay/Waiting/index.ts
  frontend/src/pages/MultiPlay/index.ts
  frontend/src/pages/Profile/index.ts
  frontend/src/pages/Register/index.ts
  frontend/src/pages/Result/index.ts
  frontend/src/pages/Settings/User/index.ts
  frontend/src/pages/SinglePlay/Game/index.ts
  frontend/src/pages/SinglePlay/Select/index.ts
  frontend/src/pages/Tournament/Game/index.ts
  frontend/src/pages/Tournament/Waiting/index.ts
  frontend/src/pages/Tournament/WaitingNextMatch/index.ts
  frontend/src/pages/Tournament/index.ts
  frontend/src/utils/fetcher.ts
  frontend/src/utils/language.ts
  frontend/tsconfig.json
Labels: Problem: bug

#230 FIX: 現在の実装をいったんリセットしてドラフトだけ#212
  api/pong/consumers.py
  api/pong/fixtures/initial_data.json
  api/pong/game_logic.py
  api/pong/migrations/0001_initial.py
  api/pong/models.py
  api/pong/routing.py
  api/pong/serializers.py
  api/pong/tournament_consumers.py
  frontend/src/models/Tournament/TournamentGameManager.ts
  frontend/src/models/interface.ts
  frontend/src/pages/Tournament/Game/index.html
  frontend/src/pages/Tournament/Game/index.ts
  frontend/src/pages/Tournament/Game/style.css
  frontend/src/pages/Tournament/Waiting/index.html
  frontend/src/pages/Tournament/Waiting/index.ts
  frontend/src/pages/Tournament/Waiting/style.css
  frontend/src/pages/Tournament/WaitingNextMatch/index.html
  frontend/src/pages/Tournament/WaitingNextMatch/index.ts
  frontend/src/pages/Tournament/WaitingNextMatch/style.css
Labels: Problem: bug, Type: improvement, WIP

#236 ADD: トーナメントの一回戦がプレイできる#212
  api/pong/tournament_consumers.py
  frontend/src/models/Game/type.ts
  frontend/src/models/Tournament/TournamentGameManager.ts
  frontend/src/models/interface.ts
  frontend/src/pages/Tournament/Game/index.html
  frontend/src/pages/Tournament/Game/index.ts
  frontend/src/pages/Tournament/Game/style.css
Labels: Type: new feature

#239 ADD: トーナメント機能の完成まで #212
  api/pong/routing.py
  api/pong/tournament_consumers.py
  frontend/src/main.ts
  frontend/src/models/Tournament/TournamentGameManager.ts
  frontend/src/pages/Tournament/Game/index.ts
  frontend/src/pages/Tournament/Waiting/index.ts
  frontend/src/pages/Tournament/WaitingNextMatch/index.html
  frontend/src/pages/Tournament/WaitingNextMatch/index.ts
  frontend/src/pages/Tournament/WaitingNextMatch/style.css
Labels: Type: new feature

#250 FIX: シングルプレイの正しいスコア保存 #242
  frontend/src/models/Game/repository.ts
Labels: Problem: bug

#247 FIX: https, wssを使用する #244
  .env.sample
  .gitignore
  Makefile
  README.md
  api/core/settings.py
  api/entrypoint.sh
  api/pong/routing.py
  api/pong/tournament_consumers.py
  docker-compose.yml
  frontend/src/config/config.ts
  frontend/src/pages/MultiPlay/Game/index.ts
  frontend/src/pages/MultiPlay/Waiting/index.ts
  frontend/src/pages/Tournament/Game/index.ts
  frontend/src/pages/Tournament/Waiting/index.ts
  frontend/src/pages/Tournament/WaitingNextMatch/index.ts
  frontend/vite.config.ts
  scripts/generate_certs.sh
Labels: Problem: security, Type: improvement

#252 Hrinka2/design level select#219
  frontend/public/assets/logo_easy.png
  frontend/public/assets/logo_hard.png
  frontend/public/assets/logo_medium.png
  frontend/public/assets/logo_oni.png
  frontend/src/pages/SinglePlay/Game/LocalGame.ts
  frontend/src/pages/SinglePlay/Select/Background.ts
  frontend/src/pages/SinglePlay/Select/index.html
  frontend/src/pages/SinglePlay/Select/index.ts
  frontend/src/pages/SinglePlay/Select/style.css
Labels: Type: design

#251 ADD: ゲームプレイの履歴表示 #248
  api/pong/models.py
  api/pong/serializers.py
  api/pong/urls.py
  api/pong/views.py
  frontend/src/models/User/repository.ts
  frontend/src/models/User/type.ts
  frontend/src/pages/Profile/index.html
  frontend/src/pages/Profile/index.ts
  frontend/src/pages/Profile/style.css
  frontend/src/utils/date.ts
Labels: Type: improvement, WIP

#283 ELK バインドボリューム使えない問題
  ELK/elasticsearch/Dockerfile
  ELK/kibana/Dockerfile
  ELK/logstash/Dockerfile
  ELK/setup/Dockerfile
  docker-compose.elk.yml
Labels: Problem: bug, WIP

#292 UPDATE: シングルプレイのAI弱体化計画 #290
  Makefile
  frontend/src/pages/SinglePlay/Game/LocalGame.ts
Labels: Type: improvement

#305 FIX: make lintがえぐいことになっている #287
  frontend/src/models/Game/repository.ts
  frontend/src/models/interface.ts
  frontend/src/pages/Home/Background.ts
  frontend/src/pages/Home/Background2.ts
  frontend/src/pages/Home/index.ts
  frontend/src/pages/Profile/index.ts
  frontend/src/pages/SinglePlay/Game/Utils/EventEmitter.ts
  frontend/src/pages/Tournament/Waiting/index.ts
  frontend/src/utils/fetcher.ts
  frontend/src/utils/form.ts
Labels: Problem: bug, Type: cleanup, WIP
